### PR TITLE
Update Dependencies

### LINKED ISSUE #12: ERROR LOADING PLUGIN homebridge-bomgovau
Hi.
Recently installed this plugin but it's not loading causing the line `No plugin was found for the accessory "BOMgovau" in your config.json. Please make sure the corresponding plugin is installed correctly.` to show up in the log. Digging a bit deeper the following also appears in the log...

```
[15/10/2021, 9:39:44 pm] ====================
[15/10/2021, 9:39:44 pm] ERROR LOADING PLUGIN homebridge-bomgovau:
[15/10/2021, 9:39:44 pm] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/lib/node_modules/homebridge-bomgovau/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of /usr/lib/node_modules/homebridge-bomgovau/node_modules/node-fetch/src/index.js from /usr/lib/node_modules/homebridge-bomgovau/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /usr/lib/node_modules/homebridge-bomgovau/node_modules/node-fetch/src/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/lib/node_modules/homebridge-bomgovau/node_modules/node-fetch/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-bomgovau/index.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
[15/10/2021, 9:39:44 pm] ====================

```
Installed versions
Homebridge v1.3.5
Node.js v14.18.0
Npm 6.14.15

Thanks,
Shannon

### PR DESCRIPTION
**Pull request by mitch7391**
Should fix #12.

### CODE REVIEW

**Comment by mitch7391** [comment]
Hey @SteveCohen, how are we feeling about this one? I have not been able to re-install the plugin during all of this time and would be keen to get it back in my system :)

**Comment by SteveCohen** [comment]
Thanks Mitch,
The change looks simple, but as you've not been able to install your fork on your own system successfully, I am reluctant to accept the PR. I'm unable to test it myself at the moment as I'm travelling over christmas. And once it's accepted I'll also need to push it to NPM -- again, something I can do when i'm home.

Will look at this again when I'm back at home in January. Thanks for investigating it and submitting the PR, in the meantime.

**Comment by mitch7391** [comment]
No worries @SteveCohen, that is completely understandable and I would be a little hesitant myself with my own repo. I was hoping you were able to do a local test in the mean time; but if you are away on holidays then that makes complete sense! :) also sorry for rushing you. 

I will see if I can work on why I cannot get my fork of your plugin to install on my RPi. As I said I made this exact same change for another plugin and had no issues installing a local copy to my RPi for testing. I had wondered if it has anything to do with the licence you have (I do not know much about these) or if it is something to do with the plugin identifier issue. NPM seem to be really vague with their errors... Something new for me to try and learn! Enjoy your holidays and time off :)

**Comment by mitch7391** [comment]
If you are curious; the error I am facing while trying to install locally is the following:

```shell
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/homespun/hap-nodejs-community-types.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-29T08_10_45_162Z-debug-0.log
```
Google is not helping me too much, so I might turn to reddit.

**Comment by cmlpreston** [comment]
For those who want to update dependencies themselves in the meantime, from /usr/local/lib/node_modules/homebridge-bomgovau/node_modules (or wherever the package is installed, using sudo as needed etc.): 

$ npm install node-fetch@2.6.6 --save 

should do the trick and update the package.json for you. I don't think I needed to update fakegato-history, but I just checked and it is updated, so maybe I did. I tried lots of things before the simple method above.

**Comment by mitch7391** [comment]
@cmlpreston thank you for this piece of information; this will get the plugin back in my system for the time being by the sounds! 

I have worked out my issue with trying to install my fork locally for testing is due to an issue with installing the dependency `hap-nodejs-community-types`, as highlighted in the errors; it just was not clear to me as a beginner. I am still not sure why this dependency refuses to install; I wonder if a similar method to your suggestion might get me around it.

**Comment by cmlpreston** [comment]
Actually, I was getting an error like that when trying to retrieve some package or other yesterday. I wonder if GitHub was having some issues recently.

**Comment by mitch7391** [comment]
Hmm I would only suspect that if it happened for a small period of time or a day at most; this has been since I submitted this PR, so I wouldn't expect issues lasting for 2 weeks.

**Comment by mitch7391** [comment]
Hey Steve, thanks for merging this one and hope you enjoyed your holidays :) I still could not get that `hap-nodejs-community-types` dependancy to install as a part of my forked version for some reason. It just kept actively refusing it. I take it you saw no issues with the PR in the end?

**Comment by SteveCohen** [comment]
No issues for me! Try updating from NPM/within homebridge and let me know if you still see the errors?

**Comment by mitch7391** [comment]
Awesome, glad to hear! This was quite a curious one for me. I’ll let you know if I figure it out :)

**Pull request merged**
